' Gambas module file

'' Enum for gallery types
Public Enum GalleryType_Private = 1, GalleryType_Shared

'' Enum for the application theme to use
Public Enum APP_THEME_OS = 1, APP_THEME_LIGHT, APP_THEME_DARK

'' Enums for sync status
Public Enum SYNC_PENDING = 1, SYNC_SYNCED

'' Enums for dialog return
Public Enum DLG_CANCEL, DLG_OK

'' Enums for answer message
Public Enum QTN_NO, QTN_YES

'' Enums for save photo result 
Public Enum RESPONSE_OK, RESPONSE_FILEEXIST, RESPONSE_DBERROR, RESPONSE_ERROR


'' Enums What is the case to use
Public Enum ALBUM_ADD_ACTION, ALBUM_REMOVE_ACTION, ALBUM_MANAGE_ACTION
Public Enum TAG_ADD_ACTION, TAG_REMOVE_ACTION, TAG_MANAGE_ACTION
