' Gambas module file

' Startup module for the Advanced Shared Albums Manager on Linux

Private $Configuration As Configuration
Private $Logger As LoggerPort
Private $PhotoRepository As PhotoRepository
Private $PhotoService As PhotoService
Private $Titulo As String = "[Main] "

Private $LogMessage As LogMessage
Public Sub Main()
  Dim cFormMain As FMain

  $Configuration = New Configuration
  $Logger = $Configuration.InitializeLogger()
  $LogMessage = New LogMessage($Titulo, "Main", ("Starting Gacela") & " V" & Application.Version)
  $Logger.Info($LogMessage)
  
  $Configuration.InitializeEnvironment()
  
  $PhotoRepository = New PhotoRepository($Configuration, $Logger)
  
  $PhotoService = New PhotoService($Logger, $PhotoRepository, $Configuration)
  
  cFormMain = New FMain($Configuration, $Logger, $PhotoService)
  cFormMain.Show()
  
Catch
  $LogMessage = New LogMessage($Titulo, "Main", ("A critical problem was detected and the application will stop: ") & Error.Text)
  Print $LogMessage.ToText()
  Message.Error($LogMessage.ToText())

End
