' Gambas module file

' Startup module for the Advanced Shared Albums Manager on Linux

Private $Configuration As Configuration
Private $Logger As LoggerPort
Private $PhotoRepository As PhotoRepositoryPort
Private $FileStorage As FileStoragePort
Private $PhotoService As PhotoService
Private $AlbumService As AlbumService
Private $TagService As TagService
Private $Titulo As String = "Main"

Private $LogMessage As LogMessage
Public Sub Main()
  Dim cFormMain As FMain

  $Configuration = New Configuration
  $Logger = $Configuration.InitializeLogger()
  $LogMessage = New LogMessage($Titulo, "Main", ("Starting Gacela") & " V" & Application.Version)
  $Logger.Info($LogMessage)
  
  $Configuration.InitializeEnvironment()
  
  $PhotoRepository = DataSourceFactory.CreatePhotoRepository($Configuration, $Logger)
  $FileStorage = DataSourceFactory.CreateFileStorage($Configuration, $Logger)
  
  $PhotoService = New PhotoService($Logger, $PhotoRepository, $Configuration, $FileStorage)
  $AlbumService = New AlbumService($Logger, $PhotoRepository)
  $TagService = New TagService($Logger, $PhotoRepository)
  
  cFormMain = New FMain($Configuration, $Logger, $PhotoService, $AlbumService, $TagService)
  cFormMain.Show()
  
Catch
  $LogMessage = New LogMessage($Titulo, "Main", ("A critical problem was detected and the application will stop: ") & Error.Text)
  Print $LogMessage.ToText()
  Message.Error($LogMessage.ToText())

End
