' Gambas module file

' Startup module for the Advanced Shared Albums Manager on Linux

Private $Configuration As Configuration
Private $Log4Gambas As Log4Gambas3
Private $PhotoRepository As PhotoRepository
Private $PhotoService As PhotoService
Private $Titulo As String = "[Main] "

Public Sub Main()
  Dim cFormMain As FMain

  $Configuration = New Configuration
  $Log4Gambas = $Configuration.InitializeLogger()
  $Log4Gambas.Info(LogPrefix("Main") & ("Starting Gacela") & " V" & Application.Version)
  
  $Configuration.InitializeEnvironment()
  
  $PhotoRepository = New PhotoRepository($Configuration, $Log4Gambas)
  
  $PhotoService = New PhotoService($Log4Gambas, $PhotoRepository, $Configuration)
  
  cFormMain = New FMain($Configuration, $Log4Gambas, $PhotoService)
  cFormMain.Show()
  
Catch
  Print LogPrefix("Main") & ("A critical problem was detected and the application will stop: ") & Error.Text
  Message.Error(LogPrefix("Main") & ("A critical problem was detected and the application will stop: ") & Error.Text)

End

Private Function LogPrefix(methodName As String) As String
  
  Return $Titulo & "[" & methodName & "] "
  
End
